name: eigenspectra

dependencies:
  - python=3.5
  - astropy
  - matplotlib
  - numpy
  - scipy
  - ipython
  - csv
  - glob
  - os
  - pip:
    - nbsphinx
    - spiderman-package
    - batman
    - emcee
    - starry
    - healpy
    - fitsio
    - colorcet
